### ISSUE TITLE
[Auth] Register does not return the cookie in the headers like login does

### ISSUE THREAD

**Issue by mpekala23** [Ameelio/connect-api-nest#67]
**Describe the bug**
HeaderCookieInterceptor is not properly receiving + passing along the cookie explicitly so that the mobile client can use it.

**To Reproduce**
1. Observe that the HeaderCookieInterceptor sets `cookie: undefined` in the headers of the response object for the register endpoint.

**Expected behavior**
`cookie` should be defined and valid so the mobile client can use it with the newly authenticated + registered user

**Comment by lspdrz** [comment]
@mpekala23 This is because the register endpoint doesn't actually log a user in, it just creates the user. So no session is being made in the Connect API after a 200 from /register nor is there a cookie being passed in the HTTP response.

I'm thinking the best way to do this would be in the frontend. If a user registers successfully, we then send another request to the /login endpoint using the same credentials. In a promise chain probably? Lmk what you think

**Comment by mpekala23** [comment]
works for me, that's what I'm doing rn. Just wanted to flag it while it was still on my mind, definitely not something that can't be worked around

**Comment by gabrielsaruhashi** [comment]
@mpekala23 closing this issue as it seems to be related to the old API
